# Generated by Django 3.1.7 on 2021-03-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210328_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(null=True, verbose_name='Time of assignment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.courier'),
        ),
    ]
